version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: codementorx_postgres
    environment:
      POSTGRES_DB: codementorx_db
      POSTGRES_USER: codementorx_user
      POSTGRES_PASSWORD: @code123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codementorx_user -d codementorx_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6-alpine
    container_name: codementorx_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  django:
    build:
      context: ./backend/django_auth
      dockerfile: Dockerfile
    container_name: codementorx_django
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://codementorx_user:your-secure-password@postgres:5432/codementorx_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/django_auth:/app
    command: python manage.py runserver 0.0.0.0:8000

  fastapi:
    build:
      context: ./backend/chatbot
      dockerfile: Dockerfile
    container_name: codementorx_fastapi
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://codementorx_user:your-secure-password@postgres:5432/codementorx_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/chatbot:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: codementorx_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_DJANGO_API_URL=http://localhost:8000
      - VITE_FASTAPI_URL=http://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000

volumes:
  postgres_data:
  redis_data: