# Generated by Django 4.2.7 on 2025-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot_models", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["user", "is_active", "-updated_at"],
                name="chatbot_mod_user_id_a7a852_idx",
            ),
        ),
    ]
